#!/bin/bash
# Queries the dependency graph built by build-deps.sh.
#
#   query-deps.sh why <package>        what it needs, and what needs it
#   query-deps.sh closure <package>..  everything those packages pull in
#   query-deps.sh check [distro]..     what a distro's list is missing
#   query-deps.sh declared             declared build deps vs the derived graph
#
# The graph only holds the shared library dependencies, which are derived from
# the built packages. Anything opened with dlopen, run as a program or read as
# a data file is not in it and has to be declared in the build script - see the
# comment at the top of build-deps.sh.
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASE_DIR=$( cd -- "$SCRIPT_DIR/../.." &> /dev/null && pwd )
cd "$BASE_DIR"

DEPS="${LFS_PACKAGES:-packages}/.deps"
WORK_RDEPS=$(mktemp); trap 'rm -f "$WORK_RDEPS"' EXIT
[ -f "$DEPS" ] || { echo "No dependency graph yet, run 'make deps' first"; exit 1; }

# What the binaries say. Exact, and regenerated by 'make deps'.
derived_of() { awk -F'\t' -v p="$1" '$1 == p { print $2 }' "$DEPS" | tr ' ' '\n' | grep -v '^$' || true; }

# What the build script says. This is where the dependencies live that no ELF
# header can show: a module opened with dlopen, a program run by another
# program, a data file. Without these the closure is short by exactly the kind
# of dependency which is hardest to find by testing - a distro assembles, the
# libraries all resolve, and something fails at run time.
declared_runtime_of() {
    local f
    f=$(ls scripts/packages/*/"$1".sh 2>/dev/null | head -1)
    [ -n "$f" ] || return 0
    sed -n 's/^# RUNTIME_REQUIRES:[[:space:]]*//p' "$f" | tr ' ' '\n' | grep -v '^$' || true
}

deps_of() { { derived_of "$1"; declared_runtime_of "$1"; } | sort -u; }

# every package reachable from the ones named, the argument order does not matter
closure() {
    local pending=("$@") seen=() p d
    while [ ${#pending[@]} -gt 0 ]; do
        p="${pending[0]}"; pending=("${pending[@]:1}")
        case " ${seen[*]} " in *" $p "*) continue ;; esac
        seen+=("$p")
        for d in $(deps_of "$p"); do pending+=("$d"); done
    done
    printf '%s\n' "${seen[@]}" | sort -u
}

pkglist() { grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$1" 2>/dev/null | sed 's/\.tar\.gz$//' || true; }

case "${1:-}" in
why)
    p="${2%.tar.gz}"
    [ -n "$p" ] || { echo "usage: query-deps.sh why <package>"; exit 1; }
    echo "$p needs:"
    derived_of "$p" | sort | sed 's/^/    /'
    declared_runtime_of "$p" | sort | sed 's/^/    /; s/$/   (declared, not visible in the binaries)/'
    [ -n "$(deps_of "$p")" ] || echo "    nothing - it links against no library from another package"
    echo "
needed by:"
    { awk -F'\t' -v p="$p" '{ n = split($2, d, " "); for (i = 1; i <= n; i++) if (d[i] == p) print "    " $1 }' "$DEPS"
      # the reverse direction of the declared edges, which are not in the graph
      grep -l "^# RUNTIME_REQUIRES:.*\b$p\b" scripts/packages/*/*.sh 2>/dev/null \
        | while read -r f; do echo "    $(basename "$f" .sh)   (declares it at run time)"; done
    } | sort | tee "$WORK_RDEPS"
    [ -s "$WORK_RDEPS" ] || echo "    nothing"
    ;;
closure)
    shift
    [ $# -gt 0 ] || { echo "usage: query-deps.sh closure <package>.."; exit 1; }
    closure "${@%.tar.gz}"
    ;;
check)
    shift
    distros=("$@")
    [ ${#distros[@]} -gt 0 ] || distros=($(cd distros && ls -d */ | tr -d /))
    rc=0
    for d in "${distros[@]}"; do
        [ -f "distros/$d/packages.list" ] || continue
        [ "$d" = core ] && continue
        mapfile -t listed < <( { pkglist "distros/core/packages.list"; pkglist "distros/$d/packages.list"; } | sort -u )
        mapfile -t needed < <(closure "${listed[@]}")
        # A distro may leave a package out on purpose. This graph is coarser
        # than 'make check': it says grub needs freetype because one binary of
        # grub links it, while the distro's decision is about that one binary -
        # grub-mkfont is never run, so the C++ runtime behind it is not worth
        # 207 MB. Those decisions belong in distros/<d>/deps.ignore, one
        # package per line, with the reason next to it.
        missing=$(comm -13 <(printf '%s\n' "${listed[@]}" | sort -u) <(printf '%s\n' "${needed[@]}") \
            | grep -vxF -f <(pkglist "distros/$d/deps.ignore" 2>/dev/null || true; echo "__none__") || true)
        if [ -n "$missing" ]; then
            echo "$d is missing $(echo "$missing" | wc -l) package(s) its libraries need:"
            for m in $missing; do
                want=$(awk -F'\t' -v p="$m" '{ n = split($2, x, " "); for (i=1;i<=n;i++) if (x[i]==p) { print $1; exit } }' "$DEPS")
                # a package reached only through a declared runtime edge is in
                # no derived edge, so the graph cannot say who wanted it
                [ -n "$want" ] || want="$(grep -l "^# RUNTIME_REQUIRES:.*\b$m\b" scripts/packages/*/*.sh 2>/dev/null \
                    | head -1 | xargs -r basename | sed 's/\.sh$//') (declared)"
                printf "    %-34s wanted by %s\n" "$m" "$want"
            done
            rc=1
        else
            echo "$d is closed - every library it needs is in the list"
        fi
    done
    exit $rc
    ;;
declared)
    # The two halves are meant to disagree in one direction only. A package can
    # link a library it did not need to build against - that is normal, the
    # library came in through another dependency. The other direction is the
    # interesting one: a build dependency which never shows up in the binaries
    # is either build-only, which is fine and common, or it is wrong.
    printf "%-34s %s\n" "package" "declared build deps not seen in the binaries"
    for f in scripts/packages/*/[0-9]*-make-*.sh; do
        name=$(basename "$f" .sh)
        decl=$(sed -n 's/^# BUILD_REQUIRES:[[:space:]]*//p' "$f" | head -1)
        [ -n "$decl" ] || continue
        derived=" $(awk -F'\t' -v p="$name" '$1 == p { print $2 }' "$DEPS") "
        out=""
        for d in $decl; do
            case "$derived" in *" $d "*) ;; *) out="$out $d" ;; esac
        done
        [ -n "$out" ] && printf "%-34s %s\n" "$name" "${out# }"
    done
    echo "
Packages with no BUILD_REQUIRES line at all: $(
        total=0; declared=0
        for f in scripts/packages/*/[0-9]*-make-*.sh; do
            total=$((total+1))
            grep -q '^# BUILD_REQUIRES:' "$f" && declared=$((declared+1))
        done
        echo "$((total - declared)) of $total")"
    ;;
*)
    sed -n '2,12p' "$0" | sed 's/^# \?//'
    exit 1
    ;;
esac
